services:
  database:
    image: mysql:5.7
    platform: linux/amd64
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: aroundthekorea
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
    volumes:
      - ./database/db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: application
    restart: always
    ports:
      - "8080:8080"
    environment:
      JASYPT_KEY: aroundthekorea
    depends_on:
      - database
