server:
  port: ENC(sR896rIzKHi4bGYnvr0VoQ==)
  ssl:
    key-store: ENC(Ji+6HBUVeQAAVNieWN6uLquh54lqWwrPFDWtf2/TUPo=)
    key-store-password: ENC(BXalHHYPU9Dw0FnC3l0/sQ==)
    key-store-type: ENC(8uGWQ7QH6oyp9+u6R9NPXA==)
    key-alias: ENC(UF4MtNO5t9ljS3a/43Yb/k10PclUMdR4)
spring:
  cors:
    allow-origins:
      - ENC(o4u19wOUQNasEc7QQ0OHqcEb1Vskl2isnuP5x88Nrcs=)
      - ENC(WaI6mE9sUc5hr4HEq0SQBIIzMVf0jlQo21W2e5tssEs=)
  sql:
    init:
      schema-locations: classpath:batch-schema-h2.sql
      mode: always
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
        retryer:
          period: 2000
          maxPeriod: 3000
          maxAttempts: 3

resilience4j:
  circuitbreaker:
    instances:
      spotDataApi:
        failure-rate-threshold: 70
        slow-call-rate-threshold: 50
        wait-duration-in-open-state: 60s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 20
        minimum-number-of-calls: 10
        sliding-window-type: COUNT_BASED

jasypt:
  key: ${JASYPT_KEY}

data:
  service-key: ENC(X+zbIcHSkczCFiquZUJwqEUwwOKcfbuF+XUDyhMiq3IPZIMQhFjD/rd5P+B/XVwlm0frRvgJZHDR8FjQCt75VSlLNajHEes2TP/zCcX7eDqhfrDVlS62aaJpJSADPywmHnoLfXQNAEI=)

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: DEBUG
    org.springframework.batch: DEBUG
    org.springframework.jdbc.core: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.support: DEBUG

